version: '2'
networks:
  mqtt-net:
    driver: bridge

services:
  mqtt:
    #image: bitrox/alpine-mosquitto-certbot
    build: mosquitto-docker-letsencrypt
    networks:
      - mqtt-net
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 80:80
    environment:
      - DOMAIN=mqtt.myserver.com
      - EMAIL=myemail@myprovider.com
    volumes:
      - ./mosquitto/conf/:/mosquitto/conf
      - ./mosquitto/log/:/mosquitto/log
      - ./letsencrypt:/etc/letsencrypt
      - ./scripts:/scripts
    container_name: mqtt
    restart: always